accommodation_recommendation_task:
  description: >
    - 사용자가 입력한 {location}의 위도와 경도를 GeoCoordinateTool()로 추출합니다.
    - 추출한 위도와 경도를 GoogleMapSearchTool()에 전달하여 {location} 지역의 다양한 숙소를 검색합니다.
    - GoogleMapSearchTool() 결과에서 최소 10개 이상의 다양한 숙소 이름과 data_id를 추출합니다.
    - 추출한 각 숙소 이름으로 GoogleHotelSearchTool()을 사용하여 상세 정보를 검색합니다. 이때 {check_in_date}와 {check_out_date}를 파라미터로 사용합니다.
    - GoogleHotelSearchTool() 결과에서 각 숙소의 kor_name, eng_name, description, address, url, image_url, map_url, phone_number,추출합니다.
    - 숙소 유형이 명확하지 않은 경우, 제공된 정보를 바탕으로 가장 적절한 유형을 추정합니다.
    - 각 숙소의 data_id로 GoogleReviewTool()을 사용하여 리뷰를 검색합니다.
    - GoogleReviewTool() 결과에서 각 숙소별로 고유하고 특징적인 키워드 15개를 추출합니다. 이 키워드들은 해당 숙소의 특성을 잘 나타내야 합니다.
    - 키워드 중 1개는 숙소 유형(예: 호텔, 호스텔, 모텔, 풀빌라 등)을 포함합니다. 
    - 키워드 중 1개는 반려견 동반 가능 여부를 포함합니다.
    - 키워드 중 1개는 추천 연령대를 포함합니다. 
    - 각 장소는 accommodation이라는 이름을 가지며 모두 accommodations 이라는 단일 리스트에 포함.
    - 사용자 입력 keyword와 일치하는 키워드가 많은 순서대로 accommodation 정렬.
    - 최종 결과는 최소 10개 이상의 다양한 숙소 정보를 포함해야 합니다.
  expected_output: >
    다양한 유형의 숙소 정보가 포함된 JSON 형식의 데이터 (최소 10개 이상의 숙소)
  agent: accommodation_recommendation_expert