accommodation_recommendation_task:
  description: >
    - GeoCoordinateTool()을 사용하여 {location}의 위도 계산 후 GoogleMapTool()로 전달.
    - {location} 지역의 다양한 숙소를 GoogleMapTool()을 통해 검색.
    - GoogleMapTool() 결과에서 최소 10개 이상의 다른 title과 cid, fid, latitude, longitude, website, phoneNumber,description, address,type, website, thumbnailUrl를 추출합니다.
    - {location}, {check_in_date}와 {check_out_date}을 사용하여 GoogleHotelSearchTool()으로 예약 가능한 숙소의 이름을 추출합니다. 
    - GoogleHotelSearchTool()의 검색 결과인 이름과 GoogleMapTool() 결과 title을 비교하여 두 곳에 존재하는 속소 이름의 리스트를 만듭니다.
    - 두 곳에 존재하는 속소 이름의 리스트의 cid, fid로 GoogleReviewTool()을 사용하여 리뷰를 검색합니다.
    - GoogleReviewTool()로 검색한 리뷰에서 각 숙소별로 고유하고 특징적인 숙소 키워드 반드시 10개를 추출합니다. 이 키워드들은 해당 숙소의 특성을 잘 나타내야 합니다.
    - 1번 키워드는 반드시 숙소 type을 포함합니다. 
    - 2번 키워드는 반드시 추천 연령대(20,30,40,50,60,70,80 중 하나)를 포함합니다. 
    - 3번 키위드는 반드시 추천 단체(친구, 여인, 가족 중 하나)를 포함합니다. 
    - 4번 키워드는 반드시 반려견 동반 가능 여부를 확인하여 포함합니다.
    - 5번 키워드는 반드시 해당 숙소에 있는 부대 시설을 포함합니다. 
    - 6번 부터 10번 까지는 검색한 리뷰를 기반으로 채워넣는다.  
    - 숙소 정렬 시 주의할점 : 
    - 1. prompt가 있을 경우, prompt에서 키워드를 추출, 숙소 키워드와 비교하여 일치하는 키워드가 많은 숙소를 상위에 우선 정렬합니다. prompt가 없을 경우, 사용자 입력 keyword와 일치하는 키워드가 많은 숙소를 상위에 우선 정렬합니다. 
    - 2. prompt에서 추출한 키워드 혹은 사용자 입력 keyword에 숙소 type이 있다면 반드시 일치하는 숙소 type을 가진 숙소를 상위에 위치하도록 합니다.
    - 3. 사용자 입력 age_group과 숙소 추천 연령대가 일치하는 숙소를 상위에 위치합니다.
    - 최종 결과는 7개의 다양한 숙소 정보를 포함해야 합니다.
  expected_output: >
    다양한 유형의 숙소 정보가 포함된 텍스트 (7개의 숙소)
  agent: accommodation_recommendation_expert


cafe_research_task:
  description: >
    고객이 최고의 여행을 할 수 있도록 고객의 상황과 취향에 맞는 카페를 고르기 위해 카페를 조사하고 최종적으로 고객의 needs를 만족하는 {n}개의 카페 정보를 반환해주세요.
    tool 사용시 검색어는 "{main_location} 카페"를 입력해주세요

    tool output을 참고하여 카페의 특징을 분석하고 description을 작성해주세요
    description에는 카페의 리뷰를 분석해 사람들이 공통적으로 좋아했던 카페의 주요 특징과 메뉴 이름을 포함해 간략히 적어주세요.
    description에는 절대 나이, 연령대에 대한 언급을 하지마세요.
    
    카페는 반드시 고객의 여행 지역인 {main_location}에 위치해야하고, 폐업 또는 휴업하지 않은 카페여야합니다. 
    고객의 선호도({concepts})와, 주 연령대({ages})와 요구사항({user_prompt})을 반영해 카페를 찾아주세요.
    고객의 선호도({concepts})와 요구사항({user_prompt})에 "프랜차이즈"가 포함되지 않는 경우, 프랜차이즈 카페는 제외해주세요.
    프랜차이즈 카페 : 스타벅스, 투썸플레이스, 이디야, 빽다방, 메가커피 등 전국에 매장이 5개 이상인 커피 전문점 
    
    모르는 정보는 지어내지 말고 "정보 없음"으로 작성하세요. 
  expected_output: >
    반드시 서로 다른 이름의 {n}개의 카페를 반환해주세요.  
    다음 4가지 필드는 항상 해당 값으로 고정해주세요
    spot_category: 3
    order: 0
    day_x: 0
    spot_time: null 
  agent: cafe_researcher

cafe_reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: cafe_reporting_analyst
