accommodation_recommendation_task:
  description: >
    - GeoCoordinateTool()을 사용하여 {location}의 위도 계산 후 GoogleMapTool()로 전달.
    - {location} 지역의 다양한 숙소를 GoogleMapTool()을 통해 검색.
    - GoogleMapTool() 결과에서 최소 10개 이상의 다양한 숙소 이름과 cid, fid, latitude, longitude, website, phoneNumber,description, address,type, website, thumbnailUrl를 추출합니다.
    - 추출한 각 숙소 이름으로 GoogleHotelSearchTool()을 사용하여 상세 정보를 검색합니다. 이때 {check_in_date}와 {check_out_date}를 파라미터로 사용합니다.
    - GoogleHotelSearchTool()의 검색 결과로 찾은 해당 일정에 예약 가능한 모든 숙소의 이름을 추출합니다.
    - 각 숙소의 cid, fid로 GoogleReviewTool()을 사용하여 리뷰를 검색합니다.
    - GoogleReviewTool() 결과에서 각 숙소별로 고유하고 특징적인 키워드 15개를 추출합니다. 이 키워드들은 해당 숙소의 특성을 잘 나타내야 합니다.
    - 키워드 중 1개는 반드시 숙소 type을 포함합니다. 
    - 키워드 중 1개는 반드시 반려견 동반 가능 여부를 포함합니다.
    - 키워드 중 1개는 반드시 추천 연령대(20,30,40,50,60,70,80 중 하나)를 포함합니다. 
    - 키워드 중 1개는 반드시 추천 단체(친구, 여인, 가족 중 하나)를 포함합니다. 
    - 각 장소는 accommodation이라는 이름을 가지며 모두 accommodations 이라는 단일 리스트에 포함합니다. 
    - 사용자 입력 keyword와 일치하는 키워드가 많은 순서대로 accommodation를 상위에 우선 정렬합니다. 
    - 최종 결과는 최소 10개 이상의 다양한 숙소 정보를 포함해야 합니다.
  expected_output: >
    다양한 유형의 숙소 정보가 포함된 JSON 형식의 데이터 (최소 10개 이상의 숙소)
  agent: accommodation_recommendation_expert