name: Backend CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to AWS ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 3. Build and tag Docker image
      - name: Build Docker image
        run: |
          docker build --cache-from -t ${{ secrets.ECR_REPOSITORY_URI }}/backend:latest .

      # 4. Push Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY_URI }}/backend:latest

      # 5. Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.ECR_REPOSITORY_URI }}/backend:latest
            docker stop backend || true
            docker rm backend || true
            docker run -d --name backend -p 8000:8000 ${{ secrets.ECR_REPOSITORY_URI }}/backend:latest
